package entities;

import java.io.Serializable;
/**
 * Represents the income and order information for a supplier.
 * This class implements {@link Serializable} to allow its instances to be serialized.
 */
public class SupplierIncome implements Serializable {
	private static final long serialVersionUID = 1L;
	private int supplierID;
	private String supplierName;
	private int incomes;
	private int totalOrders;
    /**
     * Constructs a {@link SupplierIncome} instance with the specified supplier ID, name, and income.
     * 
     * @param supplierID the unique identifier of the supplier
     * @param supplierName the name of the supplier
     * @param incomes the income generated by the supplier
     */
	public SupplierIncome(int supplierID, String supplierName, int incomes) {
		this.incomes=incomes;
		this.supplierID=supplierID;
		this.supplierName=supplierName;
	}
	   /**
     * Constructs a {@link SupplierIncome} instance with the specified supplier ID, name, income, and total orders.
     * 
     * @param supplierID the unique identifier of the supplier
     * @param supplierName the name of the supplier
     * @param incomes the income generated by the supplier
     * @param totalOrders the total number of orders for the supplier
     */
	public SupplierIncome(int supplierID, String supplierName, int incomes, int totalOrders) {
		this.incomes=incomes;
		this.supplierID=supplierID;
		this.supplierName=supplierName;
		this.totalOrders=totalOrders;
	}
	public int getSupplierID() {
		return this.supplierID;
	}
	public int getIncome() {
		return this.incomes;
	}
	public String getSupplierName() {
		return this.supplierName;
	}
	public int getTotalOrders() {
		return this.totalOrders;
	}
}
