package gui.loader;

public enum Screen {
	CEO_SCREEN,
	MANAGER_SCREEN,
	CUSTOMER_SCREEN,
	MONTHLY_REPORT_SCREEN,
	MONTHLY_REPORT_SCREEN_TWO,
	REGISTRATION_SCREEN,
	CHOOSE_RESTAURANT_SCREEN,
	RESTAURANT_MENU_SCREEN,
	MY_ORDERS_SCREEN,
	SUPPLIER_SCREEN,
	EMPLOYEE_SCREEN,
	ADD_ITEM_SCREEN,
	REMOVE_ITEM_SCREEN,
	EDIT_ITEM_SCREEN;
}
