package gui.loader;

public enum Screen {
	CEO_SCREEN,
	MANAGER_SCREEN,
	MONTHLY_REPORT_SCREEN,
	REGISTRATION_SCREEN,
	NEW_ORDER_SCREEN,
	MY_ORDERS_SCREEN,
	SUPPLIER_SCREEN,
	EMPLOYEE_SCREEN,
	ADD_ITEM_SCREEN,
	REMOVE_ITEM_SCREEN,
	EDIT_ITEM_SCREEN,
	QUARTERLY_REPORT_SCREEN
	;
}
