package enums;

//ENUM for Server Actions - for comfort
public enum ServerResponse {
	UPDATE_CONNECTION_INFO, //call client with STRING containing his IP + HOST + STATUS
	USER_FOUND,
	USER_NOT_FOUND,
	BRANCH_MANAGER_DATA,
	CEO_DATA,
	CEO_FOUND,
	MANAGER_FOUND,
	CUSTOMER_FOUND,
	SUPPLIER_FOUND,
	EMPLOYEE_FOUND,
	ADD_SUCCESS,
	ADD_FAIL,
	DELETE_ITEM_SUCCESS,
	DELETE_ITEM_FAIL,
	UPDATE_ITEM_SUCCESS,
	UPDATE_ITEM_FAIL,
	UNREGISTERED_CUSTOMERS_FOUND
	;
}
